CFLAGS=-Wall -g

all: mult_test sub_test add_test pow_test

mult_test: ../src/istr.o

sub_test: ../src/istr.o

add_test: ../src/istr.o

pow_test: ../src/istr.o

clean:
	rm -f *.o mult_test sub_test add_test pow_test
